//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstellationStation.TestRunner {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class TestRunnerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestRunnerSettings defaultInstance = ((TestRunnerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestRunnerSettings())));
        
        public static TestRunnerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Tests\\bin\\Debug\\ConstellationStation.Tests.dll")]
        public string UnitTestsPath {
            get {
                return ((string)(this["UnitTestsPath"]));
            }
        }
    }
}
