//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ConStation.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   120
#define IDR_STARFIELD                   120
#define IDR_CONSTELLATION               121
#define IDC_POINT                       140
#define IDC_ROTXY                       141
#define IDC_ROTZ                        142
#define IDC_EDIT                        143
#define IDC_EDITX                       144
#define IDC_ALINE                       145
#define IDC_ALINEX                      146
#define IDC_DLINE                       147
#define IDC_DLINEX                      148
#define IDD_CONST_NAME                  150
#define IDD_SHOW_HIDE                   151
#define IDD_LOCATION                    153
#define IDD_OPTIONS_GENERAL             159
#define IDD_OPTIONS_STAR                160
#define IDD_OPTIONS_CONST               161
#define IDD_OPTIONS_TERR                162
#define IDD_TIME                        163
#define IDD_OPTIONS_COLORS              164
#define IDD_OPTIONS_SUN                 165
#define IDC_CONST_NAME                  1014
#define IDC_CONST_LIST                  1021
#define IDC_SHOWALL                     1027
#define IDC_HIDEALL                     1028
#define IDC_INVERT                      1029
#define IDC_TERR_NEW                    1030
#define IDC_ROUGHNESS                   1035
#define IDC_TERR_ROUGHNESS              1035
#define IDC_TERR_COLOR                  1036
#define IDC_ROUGHNESS_TXT               1041
#define IDC_TERR_ROUGHNESS_TXT          1041
#define IDC_DATETIMEPICKER2             1045
#define IDC_DATETIMEPICKER              1045
#define IDC_CONST_LINECOLOR             1074
#define IDC_CONST_NORMCOLOR             1074
#define IDC_CONST_ACTIVECOLOR           1075
#define IDC_CONST_LINECOLORPREV         1076
#define IDC_CONST_SELCOLOR              1076
#define IDC_CONST_STARCOLOR             1077
#define IDC_TERR_WINCOLOR               1078
#define IDC_TERR_TEXTURED               1079
#define IDC_COLOR_TERRSPR               1079
#define ID_CONST_TOGGLE                 1080
#define IDC_CONST_VISIBLE               1080
#define IDC_CONST_LABELED               1081
#define IDC_COLOR_TERRSUM               1081
#define ID_STARS_TOGGLE                 1082
#define IDC_COLOR_TERRFAL               1082
#define IDC_STARS_LABELED               1083
#define IDC_TERR_VISIBLE                1084
#define IDC_TERR_SEASONS                1086
#define IDC_STARS_CONTRAST              1090
#define IDC_STARS_GAMMA                 1091
#define IDC_STARS_LIMMAG                1092
#define IDC_STARS_LIMMAG_TXT            1093
#define IDC_STARS_VISIBLE               1094
#define IDC_STARS_TEXTURED              1095
#define IDC_STARS_COLORED               1096
#define IDC_TERR_DEFAULTS               1099
#define IDC_CONST_DEFAULTS              1101
#define IDC_STARS_DEFAULTS              1103
#define IDC_TERR_COLOR_PREV             1104
#define IDC_CONST_NORMCOLOR_PREV        1106
#define IDC_CONST_SELCOLOR_PREV         1107
#define IDC_CONST_ACTIVECOLOR_PREV      1108
#define IDC_CONST_STARCOLOR_PREV        1109
#define IDC_TERR_WINCOLOR_PREV          1110
#define IDC_CONST_STARSCOLORED          1111
#define IDC_TERR_SPRCOLOR_PREV          1113
#define IDC_TERR_SUMCOLOR_PREV          1115
#define IDC_TERR_FALCOLOR_PREV          1116
#define IDC_COLOR_DEFAULTS              1117
#define IDC_COLOR_STARCOLORED           1118
#define IDC_COLOR_CONSTNORM             1119
#define IDC_COLOR_CONSTSEL              1120
#define IDC_COLOR_CONSTACTIVE           1121
#define IDC_COLOR_CONSTSTAR             1122
#define IDC_SUN_VISIBLE                 1124
#define IDC_SUN_SHINE                   1125
#define IDC_SUN_DEFAULTS                1126
#define ID_STARF_NEWRANDOM              32772
#define ID_STARF_NEWACTUAL              32773
#define ID_STARF_OPEN                   32774
#define ID_STARF_SAVE                   32775
#define ID_STARF_SAVEAS                 32776
#define ID_STARF_ROTATE                 32780
#define ID_CONST_ADD                    32800
#define ID_CONST_DELETE                 32801
#define ID_CONST_RENAME                 32802
#define ID_CONST_HIDE                   32803
#define ID_CONST_ALINE                  32820
#define ID_CONST_DLINE                  32821
#define ID_CONST_LIST                   32822
#define ID_CONST_SHOWHIDE               32841
#define ID_CONST_SHOWALL                32842
#define ID_CONST_HIDEALL                32843
#define ID_TERR_NEW                     32850
#define ID_STARF_TIME                   32851
#define ID_STARF_DATE                   32852
#define ID_STARF_SPEED                  32853
#define ID_OPTIONS_TIME                 32855
#define ID_OPTIONS_GENERAL              32862
#define ID_OPTIONS_STAR                 32865
#define ID_OPTIONS_CONST                32866
#define ID_OPTIONS_TERR                 32868
#define ID_TERR_TOGGLE                  32869
#define ID_OPTIONS_LOCATION             32870
#define ID_OPTIONS_TERRAIN              32871
#define ID_OPTIONS_SUN                  32872
#define ID_SUN_TOGGLE                   32874
#define ID_SUNSHINE_TOGGLE              32875

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32876
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
